/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package io.spine.gradle.javascript.task

import io.spine.gradle.SpineTaskGroup
import io.spine.gradle.TaskName
import io.spine.gradle.named
import io.spine.gradle.register
import io.spine.gradle.report.license.generateLicenseReport
import org.gradle.api.Task
import org.gradle.api.tasks.TaskContainer
import org.gradle.api.tasks.TaskProvider

/**
 * Registers [npmLicenseReport] task for including NPM dependencies into license reports.
 *
 * The task depends on [generateLicenseReport].
 *
 * Here's an example of how to apply it in `build.gradle.kts`:
 *
 * ```
 * import io.spine.gradle.javascript.javascript
 * import io.spine.gradle.javascript.task.clean
 *
 * // ...
 *
 * javascript {
 *     tasks {
 *         licenseReport()
 *     }
 * }
 * ```
 */
@Suppress("unused")
fun JsTasks.licenseReport()  {
    npmLicenseReport().also {
        generateLicenseReport.configure {
            finalizedBy(it)
        }
    }
}

private val npmLicenseReportName = TaskName.of("npmLicenseReport")

/**
 * Locates `npmLicenseReport` task in this [TaskContainer].
 *
 * The task generates the report on NPM dependencies and their licenses.
 */
val TaskContainer.npmLicenseReport: TaskProvider<Task>
    get() = named(npmLicenseReportName)

private fun JsTasks.npmLicenseReport() =
    register(npmLicenseReportName) {

        description = "Generates the report on NPM dependencies and their licenses."
        group = SpineTaskGroup.name

        doLast {

            // The script below generates license report for NPM dependencies and appends it
            // to the report for Java dependencies generated by `generateLicenseReport` task.

            npm("run", "license-report")
        }
    }
