#!/usr/bin/env bash

################################################################################
#
# This script pulls the project configuration files from a remote Git repository.
#
# The code of the script assumes that:
#
#   1. The project uses this code as a Git sub-module installed in the `config`
#      directory under the project root.
#
#   2. The script is called from the root of the project.
#
################################################################################

# Handle file operations related to the migration from the previous version(s).
source migrate

echo "Done."
