/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package io.spine.gradle.github.pages

object TaskName {

    /**
     * The name of the task that updates the GitHub Pages.
     */
    const val updateGitHubPages = "updateGitHubPages"

    /**
     * The name of the helper task to gather the generated Javadoc format
     * documentation generated by Dokka before updating GitHub Pages.
     */
    const val copyJavadocDocs = "copyJavadocDocs"

    /**
     * The name of the helper task to gather HTML documentation
     * generated by Dokka before updating GitHub Pages.
     */
    const val copyHtmlDocs = "copyHtmlDocs"
}
