naming:
  ClassNaming:
    excludes:
      - "**/*Test.kt" # Allows ticks-named nested test suites.
      - "**/*Spec.kt" # Allows ticks-named nested spec suites.
  MatchingDeclarationName:
    excludes:
      - "**/*Test.kt" # Allows ticks-named top-level test suites.
      - "**/*Spec.kt" # Allows ticks-named top-level spec suites.
style:
  UnusedPrivateMember:
    allowedNames: '(_|ignored|expected|serialVersionUID|about)'
    ignoreAnnotated:
      - "org.gradle.api.tasks.TaskAction"
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '3'
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
